---
services:
  foundry:
    image: felddy/foundryvtt:13
    container_name: foundry-vtt
    hostname: home-server-1
    volumes:
      - /home/neonvariant/docker/foundry:/data
    environment:
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
    ports:
      - 30000:30000/tcp
