services:
  beszel:
    image: henrygd/beszel
    container_name: beszel-hub
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - /home/neonvariant/docker/beszel:/beszel_data

  beszel-agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /var/run/systemd/private:/var/run/systemd/private:ro
    environment:
      PORT: ${PORT}
      KEY: "${KEY}"